version: "3.9"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/code
    working_dir: /code
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
